# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [7]:
import numpy as np


2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [8]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [11]:
np.full((20),1.75)

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [14]:
np.arange(4, 32, 1)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [20]:
np.arange(4, 32)[::-1]


array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [29]:
np.reshape(np.arange(1, 10, 1), (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [24]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [21]:
np.empty((4,4))

array([[4.64757490e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [22]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [30]:
np.random.random((3,3,3))

array([[[0.40588293, 0.15092607, 0.25679389],
        [0.87054736, 0.92123197, 0.26543329],
        [0.4670657 , 0.38726355, 0.12478186]],

       [[0.39461782, 0.18845348, 0.72323914],
        [0.88165767, 0.6387294 , 0.71679035],
        [0.27500786, 0.01537456, 0.17437424]],

       [[0.53838025, 0.47079797, 0.72731335],
        [0.24950889, 0.57169172, 0.14783288],
        [0.98645632, 0.78857257, 0.5901513 ]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [41]:
A = np.random.random((5,5))
print(A)
print(A.min())
print(A.max())

[[0.51119876 0.80730918 0.49912931 0.15431035 0.17451076]
 [0.48799942 0.01352385 0.50142788 0.33051758 0.81625717]
 [0.6418177  0.61021151 0.72379724 0.32805167 0.41891738]
 [0.59390348 0.1840646  0.83155442 0.78037248 0.62833634]
 [0.39840844 0.28716647 0.39779575 0.60980818 0.20253452]]
0.013523847921050547
0.8315544202869144


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [ ]:
# Write your code

13. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
# Write your code

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [ ]:
# Write your code

15. Перемножить матрицы 5x3 и 3x2

In [ ]:
# Write your code

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [ ]:
# Write your code

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [ ]:
# Write your code

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [ ]:
# Write your code

19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [21]:
# Write your code

20. Отсортировать вектор

In [ ]:
# Write your code

21. Проверить, одинаковы ли 2 numpy массива

In [ ]:
# Write your code

22. Сделать массив неизменяемым

In [ ]:
# Write your code

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [ ]:
# Write your code

24. Создать массив любой размерности состоящий из int и string

In [ ]:
# Write your code

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [22]:
# Write your code

26. Преобразовать массив из float в int

In [ ]:
# Write your code

27. Отнять среднее из каждой строки в матрице

In [23]:
# Write your code

28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [ ]:
# Write your code

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
# Write your code

## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [ ]:
# Write your code

2. Создать вектор состящий из 10 элементов

In [ ]:
# Write your code

3. Создать тензор из python list

In [ ]:
# Write your code

4. Создать тензор из np.array

In [ ]:
# Write your code

5. Создать тензор с нормальным распределением

In [ ]:
# Write your code

6. Создать тензор размером 3х3х3

In [ ]:
# Write your code

7. Создать единичную матрицу размером 4х5

In [ ]:
# Write your code

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [ ]:
# Write your code

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [ ]:
# Write your code

10. Создать произвольный тензор с типом данных int8

In [ ]:
# Write your code

11. Изменить тип данных из пункта 10 на int64

In [ ]:
# Write your code

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [ ]:
# Write your code

13. Создать пустой тензор произвольных размеров

In [ ]:
# Write your code

14. Скалярно умножить 2 вектора

In [ ]:
# Write your code

15. Умножить матрицу на вектор

In [ ]:
# Write your code

16. Перемножить 2D матрицы 

In [ ]:
# Write your code

17. Перемножить 3D тензоры

In [ ]:
# Write your code

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [ ]:
# Write your code

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [ ]:
# Write your code

20. Создать матрицу и вывести сумму по каждой строке

In [ ]:
# Write your code

20. Создать матрицу и вывести среднее по каждому столбцу

In [ ]:
# Write your code

21. Создать 2 вектора и сконкатенировать по 1 оси

In [ ]:
# Write your code

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [ ]:
# Write your code